// Generated by Vue on Rails https://github.com/vueonrails/vueonrails
// Generate a component part with test by running command `rails generate vue something --test`

import { shallowMount } from '@vue/test-utils'
import App from '@/service_form.vue'

describe('service_form.vue', () => {
    const editProps = {
        edit: true,
        id: 1
    }

    it('no props means new service', () => {
        const wrapper = shallowMount(App)

        const name = wrapper.find('input#service_name')
        const description = wrapper.find('input#description_name')

        expect(name).toBe('')
        expect(description).toBe('')
    })
})
