// Generated by Vue on Rails https://github.com/vueonrails/vueonrails 
// Generate a component part with test by running command `rails generate vue something --test`

import { mount } from '@vue/test-utils'
import App from '@/session_actions.vue'


describe('session_actions.vue', () => {
  const loginProps = {
    isLogged: true,
  };

  it('with no props is not logged in', () => {
    const wrapper = mount(App);

    expect(wrapper.find('.login_button').exists()).toBeTruthy();
    expect(wrapper.find('.sign_up_button').exists()).toBeTruthy();
    expect(wrapper.find('.logout_button').exists()).toBeFalsy()
  })

  it('with loginProps is logged in', () => {
    const wrapper = mount(App, {
      propsData : loginProps
    });


    expect(wrapper.find('.login_button').exists()).toBeFalsy();
    expect(wrapper.find('.sign_up_button').exists()).toBeFalsy();
    expect(wrapper.find('.logout_button').exists()).toBeTruthy()
  })

})
