// Generated by Vue on Rails https://github.com/vueonrails/vueonrails 
// Generate a component part with test by running command `rails generate vue something --test`

import { shallowMount, mount } from '@vue/test-utils'
import App from '@/session_actions.vue'


describe('session_actions.vue', () => {
  const loginProps = {
    isLogged: true,
    user_name: 'Carlos Santana'
  };

  it('with no props is not logged in', () => {
    const wrapper = mount(App);

    const container = wrapper.find('#session_actions');
    const loginButton = container.find('.login_button');
    const signUpButton = container.find('.sign_up_button');
    const logoutButton = container.find('.logout_button');

    expect(loginButton.text()).toBe('Iniciar sesión');
    expect(signUpButton.text()).toBe('Registrarse');
    expect(logoutButton.exists()).toBe(false);
  })

  it('with loginProps is logged in', () => {
    const wrapper = mount(App, {
      propsData : loginProps
    });

    const container = wrapper.find('#session_actions');
    const loginButton = container.find('.login_button');
    const signUpButton = container.find('.sign_up_button');
    const logoutButton = container.find('.logout_button');
    const userName = container.find('.user_name');

    expect(loginButton.exists()).toBe(false);
    expect(signUpButton.exists()).toBe(false);
    expect(logoutButton.text()).toBe('Cerrar sesión');
    expect(userName.text()).toBe(loginProps.user_name)
  })

})
