<!-- Generated by Vue on Rails https://github.com/vueonrails/vueonrails -->
<!-- The corresponding pack is app/javascript/packs/user_navbar_dropdown.js -->
<!-- Generate a Single File Component part by running command `rails generate vue something` -->

<template>
  <div class="navigation_dropdown">
    <p class="dropdown_title">{{ title }}</p>
  </div>
</template>

<script>
export default {
  props: ['title'],
  data: function() {
    return { };
  },
};
</script>

<style scoped>

</style>
