<!-- Generated by Vue on Rails https://github.com/vueonrails/vueonrails -->
<!-- The corresponding pack is app/javascript/packs/user_navbar_dropdown.js -->
<!-- Generate a Single File Component part by running command `rails generate vue something` -->

<template>
  <div class="navigation_dropdown">
    <p class="dropdown_title toggle_button" @click="toggleShow">{{ title }}</p>
    <transition name="dropdown">
      <ul v-if="show" class="dropdown_content">
        <li v-for="link in links"><a :href="link.href">{{ link.text }}</a></li>
      </ul>
    </transition>
  </div>
</template>

<script>
export default {
  props: ['title', 'links'],
  data: function() {
    return {
      show: false
    };
  },
  methods: {
    toggleShow: function () {
      this.show = !this.show
    }
  }
};
</script>

<style scoped>

</style>
