<!-- Generated by Vue on Rails https://github.com/vueonrails/vueonrails -->
<!-- The corresponding pack is app/javascript/packs/service_form.js -->
<!-- Generate another component part like this by running command `rails generate vue something` -->

<template>
  <div id="service_form">

  </div>
</template>

<script>

export default {
  data: function() {
    return {
      message: "Hello service_form!"
    };
  },
  methods: {
    onClick: function() {
      console.log("clicked");
    }
  },
};
</script>

<style scoped>

</style>