<!-- Generated by Vue on Rails https://github.com/vueonrails/vueonrails -->
<!-- The corresponding pack is app/javascript/packs/service_form.js -->
<!-- Generate another component part like this by running command `rails generate vue something` -->

<template>
  <div id="service_form">
    <h2>Crear servicio</h2>
    <form>
      <div class="field">
        <label for="service_name">Nombre: </label>
        <input type=text id="service_name" name="name" cols="40">
      </div>
      <div class="field">
        <label for="service_description">Descripción: </label>
        <textarea id="service_description" name="description" cols="40" rosw="4"></textarea>
      </div>
    </form>
  </div>
</template>

<script>

export default {
  data: function() {
    return {
      message: "Hello service_form!"
    };
  },
};
</script>

<style scoped>

</style>