<!-- Generated by Vue on Rails https://github.com/vueonrails/vueonrails -->
<!-- The corresponding pack is app/javascript/packs/service_form.js -->
<!-- Generate another component part like this by running command `rails generate vue something` -->

<template>
  <div id="service_form">
    <h2>Crear servicio</h2>
    <form>
      <div class="field">
        <label for="service_name">Nombre: </label>
        <input v-model="name" type=text id="service_name" name="name" cols="40">
      </div>
      <div class="field">
        <label for="service_description">Descripción: </label>
        <textarea v-model="description" id="service_description" name="description" cols="40" rosw="4"></textarea>
      </div>
    </form>
  </div>
</template>

<script>
import Route from '../routes'
import axios from 'axios'

export default {
  props: ['edit', 'id'],
  data: function() {
    return {
      name: '',
      description: ''
    };
  },
  created() {
    if (this.edit){
      axios.get(Route.service_path(this.id))
              .then(response => {
                this.name = response.data.service.name
                this.description = response.data.service.description
              })
              .catch(err => {})
    }
  }
};
</script>

<style scoped>

</style>