// Generated by Vue on Rails https://github.com/vueonrails/vueonrails
// A simple state management as described in https://vuejs.org/v2/guide/state-management.html
import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex);

const store = new Vuex.Store({
  state: {
    isLogged: false
  },
  mutations: {
    logout () {
      state.isLogged = false
    },
    login () {
      state.isLogged = true
    }
  }
});

export default store;
