<!-- Generated by Vue on Rails https://github.com/vueonrails/vueonrails -->
<!-- The corresponding pack is app/javascript/packs/transaction_tabs.js -->
<!-- Generate a Single File Component part by running command `rails generate vue something` -->

<template>
  <ul class="transactions-tabs nav nav-tabs font-size-x-large mb-2">
    <li class="nav-item">
      <a :href="$userAccountPath" class="all-tab nav-link" :class="allActive">Todas</a>
    </li>
    <li class="nav-item">
      <a :href="getOwnerPath()" class="offering-tab nav-link" :class="ownerActive">Ofreciendo</a>
    </li>
    <li class="nav-item">
      <a :href="getClientPath()" class="petition-tab nav-link" :class="clientActive">Pidiendo</a>
    </li>
  </ul>
</template>

<script>
export default {
  data (){
    return {
      allActive: { active:false },
      ownerActive: { active:false },
      clientActive: { active:false }
    }
  },
  mounted() {
    const params = new URLSearchParams(window.location.search)
    const transactionType = params.get('transaction_type')
    if (transactionType === 'owner') {
      this.ownerActive.active = true
    }else if (transactionType === 'client'){
      this.clientActive.active = true
    }else{
      this.allActive.active = true
    }

  },
  methods: {
    getOwnerPath() {
      return `${this.$userAccountPath}?transaction_type=owner`
    },
    getClientPath() {
      return `${this.$userAccountPath}?transaction_type=client`
    }
  }
};
</script>

<style scoped>
p {
  font-size: 2em;
  text-align: center;
}
</style>
