<!-- Generated by Vue on Rails https://github.com/vueonrails/vueonrails -->
<!-- The corresponding pack is app/javascript/packs/transaction_form.js -->
<!-- Generate another component part like this by running command `rails generate vue something` -->

<template>
  <div class="transaction-form dropdown">
    <form
      class="service-petition border-top mt-2"
      :action="$createTransactionPath"
      method="post"
      @submit.prevent="sendPetition"
    >
      <input name="utf8" type="hidden" value="✓" />
      <input type="hidden" name="authenticity_token" :value="$getCSRFToken()" />
      <input type="hidden" name="transaction[service_id]" :value="service_id" />
      <div class="field">
        <DatetimePicker></DatetimePicker>
      </div>
      <div class="field">
        <input name="transaction[duration]" />
      </div>
      <div class="field">
        <label for="addition_information">Información aditional:</label>
        <br />
        <textarea
          name="transaction[addition_information]"
          id="addition_information"
          placeholder="Añade información extra"
          rows="3"
          cols="40"
        ></textarea>
      </div>
      <div class="actions">
        <button class="send_petition btn btn-sm btn-primary">Enviar</button>
      </div>
    </form>
  </div>
</template>

<script>
import axios from "axios";
import railsFlash from "../railsFlash";
import formParams from "../formHelper";
import DatetimePicker from "./DatetimePicker/DatetimePicker";

export default {
  props: {
    service_id: {
      type: Number,
      required: true,
    },
  },
  components: {
    DatetimePicker,
  },
  data: function () {
    return {};
  },
  methods: {
    sendPetition: function (e) {
      axios
        .post(
          this.$createTransactionPath,
          formParams.getPostParams(e.target.elements)
        )
        .then((response) => {
          railsFlash.notice(response.data.message);
        })
        .catch((err) => railsFlash.alert(err.data.message));
    },
  },
};
</script>

<style scoped>
textarea {
  resize: none;
}

input,
textarea {
  font-size: 1rem;
}
</style>