<!-- Generated by Vue on Rails https://github.com/vueonrails/vueonrails -->
<!-- The corresponding pack is app/javascript/packs/transaction_form.js -->
<!-- Generate another component part like this by running command `rails generate vue something` -->

<template>
  <div class="transaction-form dropdown">
    <ul v-if="haveErrors" class="errors">
      <li
        v-for="(error, name, index) in errors"
        :key="index"
        :class="`error_${name}`"
      >
        {{ error }}
      </li>
    </ul>
    <form
      class="service-petition border-top mt-2"
      :action="$createTransactionPath"
      method="post"
      @submit.prevent="sendPetition"
    >
      <input name="utf8" type="hidden" value="✓" />
      <input type="hidden" name="authenticity_token" :value="$getCSRFToken()" />
      <input type="hidden" name="transaction[service_id]" :value="service_id" />
      <div class="field">
        <DatetimePicker
          @selected-time="updateTimeRangeInSeconds"
        ></DatetimePicker>
      </div>
      <div class="field form-group">
        <label for="transaction-duration">Duración: </label>
        <div>
          <input
            type="number"
            min="0"
            max="23"
            placeholder="Número de horas"
            :value="duration"
            @input="validateInteger"
            @keydown.delete="handleDurationDelete"
            name="transaction[duration]"
            id="transaction-duration"
            class="form-control"
          />
          <span class="duration-time-range text-muted">{{
            rangeDuration
          }}</span>
        </div>
      </div>
      <div class="field form-group">
        <label for="addition-information">Información aditional:</label>
        <br />
        <textarea
          class="form-control"
          name="transaction[addition_information]"
          id="addition-information"
          placeholder="Añade información extra"
          rows="3"
          cols="40"
        ></textarea>
      </div>
      <div class="actions">
        <button class="send-petition btn btn-primary">Enviar</button>
      </div>
    </form>
  </div>
</template>

<script>
import axios from "axios";
import railsFlash from "../railsFlash";
import formParams from "../formHelper";
import DatetimePicker from "./DatetimePicker/DatetimePicker";
import _ from "lodash/lang";

export default {
  props: {
    service_id: {
      type: Number,
      required: true,
    },
  },
  components: {
    DatetimePicker,
  },
  data: function() {
    return {
      errors: {},
      timeRangeInSeconds: -1,
      duration: 0,
      rangeDuration: "Selecciona una hora para ver el rango",
    };
  },
  watch: {
    duration() {
      if (this.timeRangeInSeconds >= 0) {
        this.setDurationRange();
      }
    },
    timeRangeInSeconds() {
      this.setDurationRange();
    },
  },
  computed: {
    haveErrors() {
      return !_.isEmpty(this.errors);
    },
  },
  methods: {
    formatMinutes(minutes) {
      return minutes < 10 ? `0${minutes}` : minutes;
    },
    toHourAndMinutes(seconds) {
      let minutes = seconds / 60;
      const hours = Math.floor(minutes / 60);
      minutes = minutes - hours * 60;
      return `${hours % 24}:${this.formatMinutes(minutes)}`;
    },
    setDurationRange() {
      const start = this.toHourAndMinutes(this.timeRangeInSeconds);
      const end = this.toHourAndMinutes(
        this.timeRangeInSeconds + this.duration * 60 * 60
      );
      this.rangeDuration = `${start} - ${end}`;
    },
    updateTimeRangeInSeconds(timeRangeInSeconds) {
      this.timeRangeInSeconds = timeRangeInSeconds;
    },
    validateInteger(event) {
      const value = parseFloat(event.target.value);
      if (_.isInteger(value) && value <= 23) {
        this.duration = value;
      }
      this.$forceUpdate();
    },
    handleDurationDelete() {
      if (this.duration < 10) {
        this.duration = 0;
      }
    },
    sendPetition: function(e) {
      axios
        .post(
          this.$createTransactionPath,
          formParams.getPostParams(e.target.elements)
        )
        .then((response) => {
          this.errors = {};
          if (!_.isUndefined(response.data.redirect)){
            Turbolinks.visit(response.data.redirect)
          }
        })
        .catch((err) => {
          railsFlash.alert(err.data.message);
          this.errors = err.data.errors;
        });
    },
  },
};
</script>

<style scoped>
textarea {
  resize: none;
}

input,
textarea {
  font-size: 1rem;
}
</style>
