<!-- Generated by Vue on Rails https://github.com/vueonrails/vueonrails -->
<!-- The corresponding pack is app/javascript/packs/transaction_form.js -->
<!-- Generate another component part like this by running command `rails generate vue something` -->

<template>
  <div class="transaction-form">
    <span class="open_petition" @click="toggleShow">Pedir</span>
    <transition>
      <form v-if="show" class="form" :action="$createTransactionPath" method="post" @submit="sendPetition">
        <input name="utf8" type="hidden" value="✓">
        <input type="hidden" name="authenticity_token" :value="csrfToken">
        <input type="hidden" name="transaction[service_id]" :value="serviceId">
        <div class="field">
          <label for="datetime"></label>
          <input type="text" name="transaction[datetime]" id="datetime" placeholder="Horario: eg. 07/07/2020 13:00">
        </div>
        <div class="field">
          <label for="addition_information"></label>
          <textarea name="transaction[addition_information]" id="addition_information" placeholder="Añade información extra"></textarea>
        </div>
        <div class="actions">
          <button class="send_petition">Enviar</button>
        </div>
      </form>
    </transition>
  </div>
</template>

<script>
  import axios from 'axios'
  import railsFlash from "../railsFlash";
  import formParams from '../formHelper'

  export default {
    props: ['serviceId'],
    data: function() {
      return {
        show: false,
        csrfToken: ''
      };
    },
    mounted() {
      this.csrfToken = this.$getCSRFToken()
    },
    methods: {
      toggleShow: function () {
        this.show = !this.show
      },
      sendPetition: function (e) {
        e.preventDefault()
        console.log(formParams.getPostParams(e.target.elements))
        axios.post(e.target.action, formParams.getPostParams(e.target.elements))
                .then(response => railsFlash.notice(response.data.message))
                .catch(err => railsFlash.alert(err.data.message))
      }
    }
  };
</script>

<style scoped>
</style>