// Generated by Vue on Rails https://github.com/vueonrails/vueonrails
// Display this Vue component on Rails View by adding `require('./AcceptPetition')` to app/javascript/application.js
// Generate a component part by running command `rails generate vue something`

import Vue from 'vue'
import AcceptPetition from '@/AcceptPetition.vue'
import {isView} from "vueonrails"

document.addEventListener('turbolinks:load', () => {
  if (!isView('account#index')) return

  const elements = document.getElementsByClassName('accept-petition')
  for (let i = 0; i < elements.length; i++){
    const el = elements.item(i)
    const props = JSON.parse(el.dataset.props)
    new Vue({
      el,
      render: h => h(AcceptPetition, { props: props })
    })
  }
})