// Generated by Vue on Rails https://github.com/vueonrails/vueonrails
// Display this Vue component on Rails View by adding `require('./CancelPetition.vue')` to app/javascript/application.js
// Generate a component part by running command `rails generate vue something`

import Vue from 'vue'
import CancelPetition from '@/CancelPetition.vue.vue'
import { isView } from "vueonrails";

document.addEventListener('turbolinks:load', () => {
  if (!isView('account#index')) return

  const elements = document.getElementsByClassName('cancel-petition')
  for(let i = 0; i < elements.length; i++){
    const el = elements.item(i)
    const props = JSON.parse(el.dataset.props)
    new Vue({
      el,
      render: h => h(CancelPetition, {props: props})
    })
  }

})