// Generated by Vue on Rails https://github.com/vueonrails/vueonrails
// Display this Vue component on Rails View by adding `require('./session_actions')` to app/javascript/application.js
// Generate a component part by running command `rails generate vue something`

import Vue from 'vue'
import App from '@/session_actions.vue'
import TurbolinksAdapter from 'vue-turbolinks'
Vue.use(TurbolinksAdapter);


document.addEventListener('turbolinks:load', () => {
  const element = document.getElementById('session_actions');
  const props = JSON.parse(element.getAttribute('data'));

  new Vue({
    el : '#session_actions',
    render: h => h(App, { props: props }),
  })
});