// Generated by Vue on Rails https://github.com/vueonrails/vueonrails
// Display this Vue component on Rails View by adding `require('./session_actions')` to app/javascript/application.js
// Generate a component part by running command `rails generate vue something`

import Vue from 'vue'
import App from '@/session_actions.vue'
import TurbolinksAdapter from 'vue-turbolinks'
Vue.use(TurbolinksAdapter);

document.addEventListener('turbolinks:load', () => {
  document.body.appendChild(document.createElement('session_actions'));
  const session_actions = new Vue({
    render: h => h(App)
  }).$mount('session_actions');
  console.log({session_actions})
});