// Generated by Vue on Rails https://github.com/vueonrails/vueonrails
// Display this Vue component on Rails View by adding `require('./transaction_tabs')` to app/javascript/application.js
// Generate a component part by running command `rails generate vue something`

import Vue from 'vue'
import TransactionsTab from '@/transaction_tabs.vue'
import { isView } from "vueonrails";

document.addEventListener('turbolinks:load', () => {
  if (!isView("account#index")) return;
  new Vue({
    el: '#transactions-tabs',
    render: h => h(TransactionsTab)
  })
})