
// Generated by Vue on Rails https://github.com/vueonrails/vueonrails
// Display this Vue component on Rails View by adding `require('./transaction')` to app/javascript/application.js
// Generate a component part by running command `rails generate vue something`

import Vue from 'vue'
import App from '@/transaction_form.vue'

document.addEventListener('DOMContentLoaded', () => {
  document.body.appendChild(document.createElement('transaction'))
  const transaction = new Vue({
    render: h => h(App)
  }).$mount('transaction')
  console.log({transaction})
})