
// Generated by Vue on Rails https://github.com/vueonrails/vueonrails
// Display this Vue component on Rails View by adding `require('./transaction')` to app/javascript/application.js
// Generate a component part by running command `rails generate vue something`

import Vue from 'vue'
import App from '@/transaction_form.vue'
import { isView } from "vueonrails";
import TurbolinksAdapter from 'vue-turbolinks'
Vue.use(TurbolinksAdapter);

document.addEventListener('turbolinks:load', () => {
  if (!isView('services#index')) return
  const vues = document.querySelectorAll('.transaction_action')
  Array.prototype.forEach.call(vues, (el) => {
    const props = {
      serviceId: el.dataset.serviceId
    }
    new Vue({
      el,
      render: h => h(App, {props: props})
    })
  })

})